name: main

on:
  push:
    branches: ['main']
jobs:
  ftp: 
    runs-on: ubuntu-latest
    steps:
    - uses : actions/checkout@v3
    - name : update 
      run: sudo apt update
    - name : install lftp
      run: sudo apt install lftp
    - name: lftp
      run: lftp ftp://ducobu:ducobu@51.91.148.161 -e "mirror -e -R index.html index_lftp.html ; quit"

