name: main

on:
  push:
    branches: ['main']
jobs:
  ftp: 
    runs-on: ubuntu-latest
    steps:
    - name: lftp
      run: ftp ftp://ducobu:ducobu@51.91.148.161 -e "mirror -e -R index.html/ /index_lftp ; quit"

